jobs:
  include:
    - language: php
      php: '5.6'
      env: TEA_UTIL_ENV="php"
    - language: php
      php: '7.0'
      env: TEA_UTIL_ENV="php"
    - language: php
      php: '7.1'
      env: TEA_UTIL_ENV="php"
    - language: php
      php: '7.2'
      env: TEA_UTIL_ENV="php"
    - language: php
      php: '7.3'
      env: TEA_UTIL_ENV="php"
    - language: go
      go: 1.12.x
      env: TEA_UTIL_ENV="go"  

script:
  - bash ut.sh ${TEA_UTIL_ENV}
